version: "3.9"
services:
  nginx:
    image: nginx:latest
    ports: 
      - 443:443
      - 80:80
    volumes:
      - ./nginx/certs/:/etc/nginx/ssl
      - ./nginx/conf/:/etc/nginx/conf.d
      - ./nginx/www/:/var/www/
  apache-server:
    image: httpd:2.4
    volumes:
      - ./apache/conf/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./apache/www/app.local/:/usr/local/apache2/htdocs/
  http-server:
    image: node:15-slim
    command: bash -c "npm install -g http-server && http-server -a 0.0.0.0"
  php-server:
    build: ./php
    volumes:
      - ./nginx/www/:/var/www/