FROM httpd:2.4

COPY ["conf/httpd-vhosts.conf", "/usr/local/apache2/conf/extra/"]

RUN sed -i \
		-e 's/^#\(Include .*httpd-vhosts.conf\)/\1/' \
		-e 's/^#\(LoadModule .*mod_proxy.so\)/\1/' \
		-e 's/^#\(LoadModule .*mod_proxy_fcgi.so\)/\1/' \
		conf/httpd.conf