FROM php:7.4.33-fpm

RUN apt-get update && \
    apt-get install -y libwebp-dev \
    libjpeg62-turbo-dev \
    libxpm-dev \
    libfreetype6-dev && \
    docker-php-ext-configure gd --enable-gd \
    --with-webp \
    --with-jpeg \
    --with-xpm \
    --with-freetype && \
    docker-php-ext-install gd